# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build:
  stage: build
  image: node:18
  tags:
    - nodejs
  before_script:
    - npm config set registry https://registry.npmmirror.com/
    - npm i -g pnpm
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm i
    - pnpm run build
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

pushToWx:
  stage: build
  image: bitnami/git
  resource_group: wx-resource-group
  tags:
    - git-client
  before_script:
    - mkdir ~/.ssh/
    - echo "${CI_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - echo "${SSH_PUSH_KEY}" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - git config user.email "kongkongye@163.com"
    - git config user.name "kongkongye"
    - git remote remove wx || true
    - git remote add wx git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git
  script:
    - git push wx HEAD:master
